export const enum VaziatBargeMamooriat {
  SARPARAST_TIME_HESABRESI,
  DAR_ENTEZAR_TAEED_MODIR_HESABRESI,
  DAR_ENTEZAR_TAEED_MOAVEN_HESABRESI,
  DAR_ENTEZAR_TAEED_JANESHIN_SAZMAN,
  DAR_ENTEZAR_TAEED_RIASATSAZMAN,
  DAR_ENTEZAR_TAEED_HEYAT_RAESE_AJA
}
